In [1]:

import pandas as pd
df = pd.read_csv("scraping.csv")
df

      Unnamed: 0                                               text
0              0  Timestamp :\n0:00 opening\n0:25 disclaimer \n1...
1              1  Team speaker Eggel, sudah punya yang Eggel Fit...
2              2  Wah kebetulan lagi nyari Speaker Bluetooth yan...
3              3  Masih QCY Box 2 tetap di hati, gua punya speak...
4              4  This is where local industries start rising. P...
...          ...                                                ...
1419        1419                                                nah
1420        1420                                          Tod bacod
1421        1421         sori gw dislike, textnya mengganggu gambar
1422        1422                                             Rinrei
1423        1423                                                 31

[1424 rows x 2 columns]

In [2]:
def clean(a,b):
    df['text']= df['text'].str.replace(a,b)

df['text'] = df['text'].astype(str).str.lower()
df.text = df.text.str.replace('\d+', '')
clean('.','')
clean(',','')
clean('-','')
clean('/','')
clean(':','')
clean(':\n','')
clean("\n",'')
clean(":\n",'')
df

C:\Users\jhonm\AppData\Local\Temp\ipykernel_91836\4199718327.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df.text = df.text.str.replace('\d+', '')
C:\Users\jhonm\AppData\Local\Temp\ipykernel_91836\4199718327.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['text']= df['text'].str.replace(a,b)

      Unnamed: 0                                               text
0              0  timestamp  opening disclaimer  iklan kopi kapa...
1              1  team speaker eggel sudah punya yang eggel fit ...
2              2  wah kebetulan lagi nyari speaker bluetooth yan...
3              3  masih qcy box  tetap di hati gua punya speaker...
4              4  this is where local industries start rising pr...
...          ...                                                ...
1419        1419                                                nah
1420        1420                                          tod bacod
1421        1421          sori gw dislike textnya mengganggu gambar
1422        1422                                             rinrei
1423        1423

[1424 rows x 2 columns]

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
data = vectorizer.fit_transform(df['text'].values.astype('U'))  ## Even astype(str) would work
print(data)

  (0, 594)	0.10288308248245431
  (0, 1683)	0.10718779443322865
  (0, 2167)	0.09450930809450947
  (0, 3680)	0.11325494516535423
  (0, 1295)	0.10288308248245431
  (0, 932)	0.18901861618901894
  (0, 2163)	0.07487449254244594
  (0, 2928)	0.11325494516535423
  (0, 3790)	0.09954408848851501
  (0, 3777)	0.10718779443322865
  (0, 1173)	0.06312887357687928
  (0, 1445)	0.05288884817728097
  (0, 12)	0.15522645567541352
  (0, 1705)	0.0891722258056151
  (0, 2178)	0.10288308248245431
  (0, 946)	0.08037691833530322
  (0, 1714)	0.0831050750734895
  (0, 2788)	0.11429897035522107
  (0, 2895)	0.14001011130480664
  (0, 3145)	0.09681593175032872
  (0, 2175)	0.0891722258056151
  (0, 3694)	0.09681593175032872
  (0, 3665)	0.08123220453734968
  (0, 173)	0.08123220453734968
  (0, 3654)	0.07176749443375455
  :	:
  (1414, 1980)	0.5164326787579152
  (1414, 1086)	0.27890084858132724
  (1414, 23)	0.22606388788294693
  (1414, 3589)	0.2664606916388117
  (1415, 1135)	0.5325178346677636
  (1415, 1227)	0.5039904625008588
  (1415, 3151)	0.45522259766894996
  (1415, 665)	0.46805022401879387
  (1415, 724)	0.19005195036204442
  (1416, 1158)	1.0
  (1417, 2948)	0.5773502691896257
  (1417, 1771)	0.5773502691896257
  (1417, 1115)	0.5773502691896257
  (1418, 2687)	0.7071067811865476
  (1418, 2701)	0.7071067811865476
  (1419, 2255)	1.0
  (1420, 198)	0.7071067811865476
  (1420, 3512)	0.7071067811865476
  (1421, 2082)	0.44136578328381515
  (1421, 3469)	0.44136578328381515
  (1421, 845)	0.44136578328381515
  (1421, 3208)	0.44136578328381515
  (1421, 1088)	0.4009456030394413
  (1421, 1205)	0.24500531583701604
  (1422, 2878)	1.0

In [4]:
from sklearn.cluster import KMeans
from sklearn.metrics.cluster import contingency_matrix
from yellowbrick.cluster import KElbowVisualizer # cluster visualizer
import matplotlib.pyplot as plt
%matplotlib inline
model = KMedoids()
visualizer = KElbowVisualizer(model, k=(1, 11))

visualizer.fit(data) # Fit the data to the visualizer
visualizer.show() # Finalize and render the figure
plt.show()

NameError: name 'KMedoids' is not defined

In [7]:
from sklearn_extra.cluster import KMedoids
kmedoids = KMedoids(n_clusters=11 ,metric='euclidean',init='k-medoids++', max_iter= 1000000,random_state=1000000).fit(data)
labels= kmedoids.labels_
print(labels)
new_df=pd.DataFrame(list(zip(df['text'],labels)),columns=['title','cluster'])
print(new_df.sort_values(by=['cluster']))

new_df.to_csv('result.csv')

[2 2 5 ... 2 2 2]
                                                  title  cluster
187   mas saya suka review mas kadang kalo ngantor s...        0
1374                                             david         1
941   tambah terus durasinya bang  jangan remehin ho...        2
940             judul lagu yg di pke no sma no apa ya??        2
939       kebetulan masih nyari soeker mini suara besar        2
...                                                 ...      ...
1188            bang bagi bagi speaker blutut bang satu       10
976                       bagi dong bang satu buat saya       10
1367                    bang bagi duit dong ribu pliiis       10
1208                                     bagi satu bang       10
1197                                bagi dong mas david       10

[1424 rows x 2 columns]